name: CI

on:
  push:
    paths:
       - "src/**"
    # branches:
    #   - main


  pull_request:
    branches:
      - main
    types: [closed]

# NODE JS APP REACT
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm install

      - name: Run tests
        run: npm run test

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: npm install

      - name: Run linting
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
      - uses: actions/checkout@v4

      - run: npm install

      - name: Build the application
        run: npm run build